/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Varvara Krauchanka (https://sketchfab.com/krauchankavarvara)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/floating-island-05041dc9277748c68bb2ff8c7b6bc063
Title: Floating Island
*/

import { useRef, useEffect, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import islandScene from "../assets/3d/island.glb";

const Island = ({
  isRotating,
  setIsRotating,
  setCurrentStage,
  setRotationSpeed,
  onFirstInteraction,
  setPlaneOrbitRadius,
  setPlaneVerticalOffset,
  setPlaneCameraDepth,
  ...props
}) => {
  const islandRef = useRef();
  const scene = useGLTF(islandScene);
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(islandScene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;
  
  // Keyboard control state
  const [keysPressed, setKeysPressed] = useState(new Set());
  const keyboardRotationSpeed = useRef(0);
  const keyboardVerticalSpeed = useRef(0);
  const keyboardCameraDepthSpeed = useRef(0);
  const planeOrbitRadius = useRef(1.0);
  const planeVerticalOffset = useRef(0);
  const planeCameraDepth = useRef(0);
  const minOrbitRadius = 0.4;
  const maxOrbitRadius = 2.5;
  const maxVerticalOffset = 1.75;
  const maxCameraDepth = 3.5;

  //Mouse/Touch
  const handlePointerDown = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(true);
    if (onFirstInteraction) onFirstInteraction();

    const clientX = event.touches ? event.touches[0].clientX : event.clientX;
    lastX.current = clientX;
  };
  const handlePointerUp = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(false);
  };
  const handlePointerMove = (event) => {
    event.stopPropagation();
    event.preventDefault();

    if (isRotating) {
      const clientX = event.touches ? event.touches[0].clientX : event.clientX;
      const delta = (clientX - lastX.current) / viewport.width;

      islandRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
      setRotationSpeed(rotationSpeed.current);
    }
  };


  const handleKeyDown = (event) => {
    const key = event.key.toLowerCase();
    const validKeys = ['w', 's', 'a', 'd', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright'];
    
    if (validKeys.includes(key)) {
      event.preventDefault();
      if (onFirstInteraction) onFirstInteraction();
      
      setKeysPressed(prev => {
        const newSet = new Set(prev);
        newSet.add(key);
        return newSet;
      });
      
      if (!isRotating) setIsRotating(true);
    }
  };
  
  const handleKeyUp = (event) => {
    const key = event.key.toLowerCase();
    const validKeys = ['w', 's', 'a', 'd', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright'];
    
    if (validKeys.includes(key)) {
      event.preventDefault();
      
      setKeysPressed(prev => {
        const newSet = new Set(prev);
        newSet.delete(key);
        return newSet;
      });
      
      // Stop rotating if no movement keys are pressed
      if (keysPressed.size <= 1) { // <= 1 because we haven't updated keysPressed yet
        setIsRotating(false);
      }
    }
  };

  useFrame(() => {
    // Handle keyboard input with momentum
    const forwardSpeed = 0.006;
    const verticalSpeed = 0.02;
    const cameraDepthSpeed = 0.05;
    const keyboardDampingFactor = 0.92;
    
    // Check for active keyboard input
    const hasForward = keysPressed.has('w') || keysPressed.has('arrowup');
    const hasVertical = keysPressed.has('s') || keysPressed.has('arrowdown');
    const hasLeftRight = keysPressed.has('a') || keysPressed.has('arrowleft') || 
                         keysPressed.has('d') || keysPressed.has('arrowright');
    
    if (keysPressed.has('w') || keysPressed.has('arrowup')) {
      keyboardRotationSpeed.current += forwardSpeed * 0.25;
      keyboardVerticalSpeed.current += verticalSpeed * 0.3;
    }
    
    if (keysPressed.has('s') || keysPressed.has('arrowdown')) {
      keyboardVerticalSpeed.current -= verticalSpeed * 0.3;
      keyboardRotationSpeed.current += forwardSpeed * 0.15;
    }
    
    if (keysPressed.has('a') || keysPressed.has('arrowleft')) {
      keyboardCameraDepthSpeed.current += cameraDepthSpeed * 0.3;
      keyboardRotationSpeed.current += forwardSpeed * 0.15;
    }
    if (keysPressed.has('d') || keysPressed.has('arrowright')) {
      keyboardCameraDepthSpeed.current -= cameraDepthSpeed * 0.3;
      keyboardRotationSpeed.current += forwardSpeed * 0.15;
    }
    
    // Apply momentum damping when keys are not pressed
    if (!hasForward) {
      keyboardRotationSpeed.current *= keyboardDampingFactor;
      if (Math.abs(keyboardRotationSpeed.current) < 0.0003) {
        keyboardRotationSpeed.current = 0;
      }
    }
    
    if (!hasVertical) {
      keyboardVerticalSpeed.current *= keyboardDampingFactor;
      if (Math.abs(keyboardVerticalSpeed.current) < 0.0003) {
        keyboardVerticalSpeed.current = 0;
      }
    }
    
    if (!hasLeftRight) {
      keyboardCameraDepthSpeed.current *= keyboardDampingFactor;
      if (Math.abs(keyboardCameraDepthSpeed.current) < 0.0003) {
        keyboardCameraDepthSpeed.current = 0;
      }
    }
    
    // Cap maximum speeds to prevent runaway acceleration - REDUCED
    const maxRotationSpeed = forwardSpeed * 1.5;
    const maxVerticalSpeed = verticalSpeed * 1.5;
    const maxCameraDepthSpeed = cameraDepthSpeed * 1.5;
    keyboardRotationSpeed.current = Math.max(-maxRotationSpeed, Math.min(maxRotationSpeed, keyboardRotationSpeed.current));
    keyboardVerticalSpeed.current = Math.max(-maxVerticalSpeed, Math.min(maxVerticalSpeed, keyboardVerticalSpeed.current));
    keyboardCameraDepthSpeed.current = Math.max(-maxCameraDepthSpeed, Math.min(maxCameraDepthSpeed, keyboardCameraDepthSpeed.current));
    
    // Apply keyboard rotation to island with momentum
    if (Math.abs(keyboardRotationSpeed.current) > 0.0003) {
      islandRef.current.rotation.y += keyboardRotationSpeed.current;
      setRotationSpeed(keyboardRotationSpeed.current);
    }
    
    // Apply vertical movement to plane
    if (Math.abs(keyboardVerticalSpeed.current) > 0.0003) {
      const newVerticalOffset = planeVerticalOffset.current + keyboardVerticalSpeed.current;
      planeVerticalOffset.current = Math.max(-maxVerticalOffset, Math.min(maxVerticalOffset, newVerticalOffset));
      if (setPlaneVerticalOffset) {
        setPlaneVerticalOffset(planeVerticalOffset.current);
      }
    }
    
    // Apply camera depth changes with momentum and limits
    if (Math.abs(keyboardCameraDepthSpeed.current) > 0.0003) {
      const newDepth = planeCameraDepth.current + keyboardCameraDepthSpeed.current;
      planeCameraDepth.current = Math.max(-maxCameraDepth, Math.min(maxCameraDepth, newDepth));
      if (setPlaneCameraDepth) {
        setPlaneCameraDepth(planeCameraDepth.current);
      }
    }
    
    // Handle mouse/touch rotation damping and keyboard momentum integration
    const hasAnyInput = hasForward || hasVertical || hasLeftRight;
    
    if (!isRotating || !hasAnyInput) {
      //Apply damping factor to mouse rotation, make plane roll smoother
      rotationSpeed.current *= dampingFactor;
      
      // Apply gentle damping to vertical offset - returns slowly to default when no input
      if (!hasVertical && Math.abs(keyboardVerticalSpeed.current) < 0.001) {
        const targetVertical = 0; // Default vertical position
        const verticalDampingFactor = 0.992; // Slightly faster return than orbit
        planeVerticalOffset.current = planeVerticalOffset.current * verticalDampingFactor + targetVertical * (1 - verticalDampingFactor);
        
        if (Math.abs(planeVerticalOffset.current - targetVertical) < 0.001) {
          planeVerticalOffset.current = targetVertical;
        }
        
        if (setPlaneVerticalOffset) {
          setPlaneVerticalOffset(planeVerticalOffset.current);
        }
      }
      
      // Apply gentle damping to camera depth - returns slowly to default when no input
      if (!hasLeftRight && Math.abs(keyboardCameraDepthSpeed.current) < 0.001) {
        const targetDepth = 0; // Default camera depth position
        const depthDampingFactor = 0.993; // Return to center
        planeCameraDepth.current = planeCameraDepth.current * depthDampingFactor + targetDepth * (1 - depthDampingFactor);
        
        if (Math.abs(planeCameraDepth.current - targetDepth) < 0.001) {
          planeCameraDepth.current = targetDepth;
        }
        
        if (setPlaneCameraDepth) {
          setPlaneCameraDepth(planeCameraDepth.current);
        }
      }

      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      // Apply any remaining momentum from mouse drag
      if (Math.abs(rotationSpeed.current) > 0.001) {
        islandRef.current.rotation.y += rotationSpeed.current;
        setRotationSpeed(rotationSpeed.current);
      }
    }
    
    const rotation = islandRef.current.rotation.y;
    const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

    if (normalizedRotation >= 0 && normalizedRotation < Math.PI / 2) {
      setCurrentStage(2);
    } else if (
      normalizedRotation >= Math.PI / 2 &&
      normalizedRotation < Math.PI
    ) {
      setCurrentStage(3);
    } else if (
      normalizedRotation >= Math.PI &&
      normalizedRotation < (3 * Math.PI) / 2
    ) {
      setCurrentStage(4);
    } else if (
      normalizedRotation >= (3 * Math.PI) / 2 &&
      normalizedRotation <= 2 * Math.PI
    ) {
      setCurrentStage(1);
    } else {
      setCurrentStage(null);
    }
  });

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [
    gl,
    handlePointerDown,
    handlePointerUp,
    handlePointerMove,
    handleKeyDown,
    handleKeyUp,
  ]);

  return (
    <a.group ref={islandRef} {...props}>
      <mesh
        geometry={nodes.defaultMaterial146.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial143.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial144.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial145.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial077.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial136.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial142.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial133.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial132.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial131.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial130.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial129.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial128.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial127.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial126.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial125.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial124.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial141.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial123.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial122.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial121.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial120.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial119.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial118.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial117.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial116.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial115.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial114.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial140.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial113.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial112.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial111.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial110.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial109.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial108.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial107.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial106.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial105.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial104.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial139.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial103.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial102.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial101.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial100.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial099.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial098.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial097.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial096.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial095.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial094.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial138.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial093.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial078.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial137.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial135.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial134.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial047.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial048.geometry}
        material={materials["layeredShader1SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial091.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial092.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial087.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial086.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial085.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial084.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial090.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial082.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial081.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial080.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial079.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial076.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial075.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial074.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial073.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial072.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial089.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial071.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial070.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial069.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial068.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial067.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial066.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial065.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial064.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial063.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial062.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial061.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial060.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial059.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial058.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial057.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial056.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial055.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial054.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial053.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial052.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial051.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial050.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial049.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial088.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial001.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial002.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial003.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial004.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial005.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial006.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial007.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial008.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial009.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial010.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial011.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial012.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial013.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial014.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial015.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial016.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial017.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial018.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial046.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial019.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial020.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial021.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial022.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial023.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial024.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial025.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial026.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial027.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial028.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial029.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial030.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial031.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial032.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial033.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial034.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial035.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial036.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial037.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial038.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial039.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial040.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial041.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial042.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial043.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial044.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial045.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
      <mesh
        geometry={nodes.defaultMaterial083.geometry}
        material={materials["lambert6SG.001"]}
        position={[-57.036, 520.783, -166.498]}
      />
    </a.group>
  );
};

export default Island;
